### ISSUE TITLE
saved file not play 

### ISSUE THREAD

**Issue by khan1hamdan** [aykuttasil/CallRecorder#27]
After save the file it show 0kb size and not play i checked in multiple device.
How can i solve this problem

**Comment by AndroidDeveloperLB** [comment]
Try various Audio Sources. 
Call recording is quite a mess on Android. Might not work on various devices, and work on others.
And each has its own configuration to try. 
I wonder though what else can be configured, because I've noticed other apps can handle cases that changing the AudioSource alone can't handle, so I've written about this here:
https://stackoverflow.com/questions/50970915/how-do-some-apps-overcome-phone-recording-restrictions
